# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd3480bbd4421d5e3408091805711f9ab2fcccd1d08ae713829c108bfdb674caea5be9d864927f56b17015047f05a9cefa82834aa9d8224b02dc7f8157d6d383

test:
  secret_key_base: 444c1bfa4dd4d6fa9a82c57fcd11ee81d937ad168269fd306ff8a52f2558cc4e2cf84ce20f71025bf3e3b259d86bb622ed92dea7f7f0b7bd0f63685e0855e678

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
